### ISSUE TITLE
Dimens are duplicated are in CompanionPane

### ISSUE THREAD

**Issue by dutta14** [microsoft/surface-duo-sdk-samples#12]
Build fails with 'duplicate resources' because some of the dimens are duplicated in 
[dimen.xml](https://github.com/microsoft/surface-duo-sdk-samples/blob/master/CompanionPane/src/main/res/values/dimen.xml) and [dimens.xml](https://github.com/microsoft/surface-duo-sdk-samples/blob/master/CompanionPane/src/main/res/values/dimens.xml).

**Comment by CesarValiente** [comment]
Addressed already in https://github.com/microsoft/surface-duo-sdk-samples/pull/15
Thanks @dutta14 for your help and work!
