### ISSUE TITLE
Deprecated method

### ISSUE THREAD

**Issue by dmcrider** [microsoft/surface-duo-sdk-samples#17]
Not sure where else to put this - please let me know if I need to move it.

I'm building a simple list app specifically targeting the Surface Duo. The documentation on [this page](https://docs.microsoft.com/en-us/dual-screen/android/sample-code/is-app-spanned?tabs=kotlin) makes reference to `WindowManager.defaultDisplay.rotation`. However, Android Studio tells me that the `defaultDisplay` getter is deprecated.

What is your recommended best practice? Is there updated documentation that will be released soon, or should we continue with deprecated methods?

**Comment by hakonstrande** [comment]
It is deprecated in Android R but still supported and ok to use in Android Q (API level 29) that the Duo ships with. We will have samples that use the replacement API context#getDisplay() in the future. For the time being, the v1 Dual Screen device (Surface Duo) will stay on API level 29 and of course always maintain backwards compatibility with the Q API set.

**Comment by dmcrider** [comment]
Thank you for that clarification.
