### ISSUE TITLE
How do I span any of the preinstalled apps on the emulator?

### ISSUE THREAD

**Issue by pistonexia** [microsoft/surface-duo-sdk-samples#3]
I know this is a dumb question. But I couldn't figure out how after 15 minutes.

**Comment by hakonstrande** [comment]
Drag the app from the "pill" at the bottom of the app screen towards the middle of the device, (towards the hinge) and the background should turn white across both screens.

**Comment by pistonexia** [comment]
Got it. Thanks. While other apps work, calendar keeps stopping.

**Comment by hakonstrande** [comment]
Thanks for the report. Yes, while the Duo OS image for the Google emulator has some included apps, it is intended for app developers interested in trying their own apps out and maybe try some out some dual-screen prototyping using the samples we have published. We have lots of work left to get to stable, reliable in-box application experience. :-) While we work on that we hope to hear from the ISVs about any issues they run into when running their apps on the Duo Android OS image running on the Google device emulator. Thanks again and let us know if/how your app(s) plan to take advantage of dual screen devices like this.
