### ISSUE TITLE
Cannot get Emulator to run

### ISSUE THREAD

**Issue by dmcrider** [microsoft/surface-duo-sdk-samples#4]
I installed the Surface Duo SDK and it appears that everything installed correctly. I found the start menu shortcut for the Emulator, but when I run it, nothing happens except an icon on the taskbar briefly appears, but is gone before it fully loads. I've even run it as an administrator, and nothing happens beyond that.

I'm running Windows 10 Pro, Version 1909 OS Build 18363.592 if that helps any. I just started the process to upgrade to Windows 10 Pro to see if that works.

I am able to run the default Android Emulator with no problems, so I believe my device meets the minimum requirements to run the Emulator.

**Comment by dmcrider** [comment]
Turns out I installed Android Studio in a place that isn't the default install path, so the run.bat file failed to find the Android Emulator. I updated the line that starts `set ANDROID_SDK_LOCATION=` to be the install location of Android Studio and now it works perfectly!

**Comment by dmcrider** [comment]
Also, it seems like you have to start the emulator before you can use it to debug in Android Studio. Studio doesn't give me the option of running on the Duo unless the emulator is already running. Not a big issue, just something to note.

**Comment by guymerin** [comment]
Thanks for the feedback @dmcrider

**Comment by hakonstrande** [comment]
We will look into addressing this either in docs or in the installer. Thank you for the info.

**Comment by ceteongvanness** [comment]
> Turns out I installed Android Studio in a place that isn't the default install path, so the run.bat file failed to find the Android Emulator. I updated the line that starts `set ANDROID_SDK_LOCATION=` to be the install location of Android Studio and now it works perfectly!

You mean change to "C:\Program Files (x86)\Android\android-sdk" for Android Studio ?

**Comment by dmcrider** [comment]
@ceteongvanness I installed Android Studio in my Documents folder so I updated that line to read `set ANDROID_SDK_LOCATION=%UserProfile%\Documents\Android` so that when `run.bat` sets the Emulator path a few lines below that, it comes out to be `C:\Users\<USER>\Documents\Android\emulator\emulator.exe`

**Comment by hakonstrande** [comment]
Feels like this one is ok to close.

**Comment by dmcrider** [comment]
Yes, that's fine.
