### ISSUE TITLE
Emulator immediately crashes

### ISSUE THREAD

**Issue by deathau** [microsoft/surface-duo-sdk-samples#5]
When I try to run the emulator, a window appears briefly then closes. I've changed the `ANDROID_SDK_LOCATION` in run.bat to point to my Android SDK location (same as my system `ANDROID_HOME` env var)
Including the cmd output for more information.
[output.txt](https://github.com/microsoft/surface-duo-sdk-samples/files/4106980/output.txt)

**Comment by dmcrider** [comment]
There seems to be an error with your path. `bad workspace: cannot find prebuilt kernel in: C:\Users\death\SurfaceDuoEmulator\artifacts\\bin\prebuilts\qemu-kernel\x86_64\kernel-qemu` between `artifacts` and `bin` you have two `\`. There should only be one. You should double check that in your run.bat file.

**Comment by deathau** [comment]
Even without the extra slash, that prebuilts folder does not exist. Is it just something missing from the zip file I downloaded?
I removed extra slashes in the bat file, but it didn't seem to make much difference to the output:
[output2.txt](https://github.com/microsoft/surface-duo-sdk-samples/files/4111122/output2.txt)

**Comment by dmcrider** [comment]
I'm not a Microsoft employee, so I'll let one of them chime in here, but it definitely looks like it didn't install correctly.

**Comment by hakonstrande** [comment]
One of our engineers here noticed a VCPU shutdown request in the log. And he did a search for this error which suggested updating HAXM library. You have 7.3.2 installed (latest is 7.5.6). Give it a try? If that does not work, then maybe try with a Google emulator in AS (Create an AVD with Android 10 and x86_64 arch)? Maybe a shot in the dark but not clear to us what might be going on.

**Comment by deathau** [comment]
Updating HAXM didn't seem to change anything.
AVDs with Android 9 were working fine, but on your suggestion I found that Android 10 ones _weren't_ on this machine which lead me to the real solution of the android emulator not actually being up-to-date. I've updated it and the emulator seems to be working fine now.
Thanks.

**Comment by rmarinho** [comment]
I had the same issue i had to update  HAXM , mine was on version 7.0.0
